# CMake generated Testfile for 
# Source directory: C:/Users/jeiler.000/iometer/github/iometer/src/qt
# Build directory: C:/Users/jeiler.000/iometer/github/iometer/src/qt/build_cov
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
include("C:/Users/jeiler.000/iometer/github/iometer/src/qt/build_cov/CTestCoverageEnv.cmake")
add_test(tst_types "C:/Users/jeiler.000/iometer/github/iometer/src/qt/build_cov/tst_types.exe" "-v2")
set_tests_properties(tst_types PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jeiler.000/iometer/github/iometer/src/qt/CMakeLists.txt;122;add_test;C:/Users/jeiler.000/iometer/github/iometer/src/qt/CMakeLists.txt;125;iometer_test;C:/Users/jeiler.000/iometer/github/iometer/src/qt/CMakeLists.txt;0;")
add_test(tst_accessspecs "C:/Users/jeiler.000/iometer/github/iometer/src/qt/build_cov/tst_accessspecs.exe" "-v2")
set_tests_properties(tst_accessspecs PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jeiler.000/iometer/github/iometer/src/qt/CMakeLists.txt;122;add_test;C:/Users/jeiler.000/iometer/github/iometer/src/qt/CMakeLists.txt;126;iometer_test;C:/Users/jeiler.000/iometer/github/iometer/src/qt/CMakeLists.txt;0;")
add_test(tst_icf "C:/Users/jeiler.000/iometer/github/iometer/src/qt/build_cov/tst_icf.exe" "-v2")
set_tests_properties(tst_icf PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jeiler.000/iometer/github/iometer/src/qt/CMakeLists.txt;122;add_test;C:/Users/jeiler.000/iometer/github/iometer/src/qt/CMakeLists.txt;127;iometer_test;C:/Users/jeiler.000/iometer/github/iometer/src/qt/CMakeLists.txt;0;")
add_test(tst_results "C:/Users/jeiler.000/iometer/github/iometer/src/qt/build_cov/tst_results.exe" "-v2")
set_tests_properties(tst_results PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jeiler.000/iometer/github/iometer/src/qt/CMakeLists.txt;122;add_test;C:/Users/jeiler.000/iometer/github/iometer/src/qt/CMakeLists.txt;128;iometer_test;C:/Users/jeiler.000/iometer/github/iometer/src/qt/CMakeLists.txt;0;")
add_test(tst_demo "C:/Users/jeiler.000/iometer/github/iometer/src/qt/build_cov/tst_demo.exe" "-v2")
set_tests_properties(tst_demo PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jeiler.000/iometer/github/iometer/src/qt/CMakeLists.txt;122;add_test;C:/Users/jeiler.000/iometer/github/iometer/src/qt/CMakeLists.txt;129;iometer_test;C:/Users/jeiler.000/iometer/github/iometer/src/qt/CMakeLists.txt;0;")
add_test(tst_protocol "C:/Users/jeiler.000/iometer/github/iometer/src/qt/build_cov/tst_protocol.exe" "-v2")
set_tests_properties(tst_protocol PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jeiler.000/iometer/github/iometer/src/qt/CMakeLists.txt;122;add_test;C:/Users/jeiler.000/iometer/github/iometer/src/qt/CMakeLists.txt;130;iometer_test;C:/Users/jeiler.000/iometer/github/iometer/src/qt/CMakeLists.txt;0;")
add_test(tst_workerpool "C:/Users/jeiler.000/iometer/github/iometer/src/qt/build_cov/tst_workerpool.exe" "-v2")
set_tests_properties(tst_workerpool PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jeiler.000/iometer/github/iometer/src/qt/CMakeLists.txt;122;add_test;C:/Users/jeiler.000/iometer/github/iometer/src/qt/CMakeLists.txt;133;iometer_test;C:/Users/jeiler.000/iometer/github/iometer/src/qt/CMakeLists.txt;0;")
add_test(tst_testrunner "C:/Users/jeiler.000/iometer/github/iometer/src/qt/build_cov/tst_testrunner.exe" "-v2")
set_tests_properties(tst_testrunner PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jeiler.000/iometer/github/iometer/src/qt/CMakeLists.txt;122;add_test;C:/Users/jeiler.000/iometer/github/iometer/src/qt/CMakeLists.txt;134;iometer_test;C:/Users/jeiler.000/iometer/github/iometer/src/qt/CMakeLists.txt;0;")
add_test(tst_icffile "C:/Users/jeiler.000/iometer/github/iometer/src/qt/build_cov/tst_icffile.exe" "-v2")
set_tests_properties(tst_icffile PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jeiler.000/iometer/github/iometer/src/qt/CMakeLists.txt;122;add_test;C:/Users/jeiler.000/iometer/github/iometer/src/qt/CMakeLists.txt;135;iometer_test;C:/Users/jeiler.000/iometer/github/iometer/src/qt/CMakeLists.txt;0;")
add_test(tst_resultswriter "C:/Users/jeiler.000/iometer/github/iometer/src/qt/build_cov/tst_resultswriter.exe" "-v2")
set_tests_properties(tst_resultswriter PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jeiler.000/iometer/github/iometer/src/qt/CMakeLists.txt;122;add_test;C:/Users/jeiler.000/iometer/github/iometer/src/qt/CMakeLists.txt;136;iometer_test;C:/Users/jeiler.000/iometer/github/iometer/src/qt/CMakeLists.txt;0;")
add_test(tst_dynamoconn "C:/Users/jeiler.000/iometer/github/iometer/src/qt/build_cov/tst_dynamoconn.exe" "-v2")
set_tests_properties(tst_dynamoconn PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jeiler.000/iometer/github/iometer/src/qt/CMakeLists.txt;122;add_test;C:/Users/jeiler.000/iometer/github/iometer/src/qt/CMakeLists.txt;137;iometer_test;C:/Users/jeiler.000/iometer/github/iometer/src/qt/CMakeLists.txt;0;")
add_test(tst_meters "C:/Users/jeiler.000/iometer/github/iometer/src/qt/build_cov/tst_meters.exe" "-v2")
set_tests_properties(tst_meters PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jeiler.000/iometer/github/iometer/src/qt/CMakeLists.txt;122;add_test;C:/Users/jeiler.000/iometer/github/iometer/src/qt/CMakeLists.txt;140;iometer_test;C:/Users/jeiler.000/iometer/github/iometer/src/qt/CMakeLists.txt;0;")
add_test(tst_pagesetup "C:/Users/jeiler.000/iometer/github/iometer/src/qt/build_cov/tst_pagesetup.exe" "-v2")
set_tests_properties(tst_pagesetup PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jeiler.000/iometer/github/iometer/src/qt/CMakeLists.txt;122;add_test;C:/Users/jeiler.000/iometer/github/iometer/src/qt/CMakeLists.txt;141;iometer_test;C:/Users/jeiler.000/iometer/github/iometer/src/qt/CMakeLists.txt;0;")
add_test(tst_mainwindow "C:/Users/jeiler.000/iometer/github/iometer/src/qt/build_cov/tst_mainwindow.exe" "-v2")
set_tests_properties(tst_mainwindow PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jeiler.000/iometer/github/iometer/src/qt/CMakeLists.txt;122;add_test;C:/Users/jeiler.000/iometer/github/iometer/src/qt/CMakeLists.txt;142;iometer_test;C:/Users/jeiler.000/iometer/github/iometer/src/qt/CMakeLists.txt;0;")
